export const IMAGE_UPLOAD_REQUEST = "IMAGE_UPLOAD_REQUEST";
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS";
export const IMAGE_UPLOAD_FAIL = "IMAGE_UPLOAD_FAIL";
export const IMAGE_UPLOAD_RESET = "IMAGE_UPLOAD_RESET";

export const IMAGE_UPDATE_REQUEST = "IMAGE_UPDATE_REQUEST";
export const IMAGE_UPDATE_SUCCESS = "IMAGE_UPDATE_SUCCESS";
export const IMAGE_UPDATE_FAIL = "IMAGE_UPDATE_FAIL";

export const IMAGE_DELETE_REQUEST = "IMAGE_DELETE_REQUEST";
export const IMAGE_DELETE_SUCCESS = "IMAGE_DELETE_SUCCESS";
export const IMAGE_DELETE_FAIL = "IMAGE_DELETE_FAIL";

export const IMAGE_GET_ALL_REQUEST = "IMAGE_GET_ALL_REQUEST";
export const IMAGE_GET_ALL_SUCCESS = "IMAGE_GET_ALL_SUCCESS";
export const IMAGE_GET_ALL_FAIL = "IMAGE_GET_ALL_FAIL";

export const IMAGE_GET_BY_ID_REQUEST = "IMAGE_GET_BY_ID_REQUEST";
export const IMAGE_GET_BY_ID_SUCCESS = "IMAGE_GET_BY_ID_SUCCESS";
export const IMAGE_GET_BY_ID_FAIL = "IMAGE_GET_BY_ID_FAIL";
