export const SAVE_QUOTATION_DATA = "SAVE_QUOTATION_DATA";

export const SEND_QUOTATION_REQUEST = "SEND_QUOTATION_REQUEST";
export const SEND_QUOTATION_SUCCESS = "SEND_QUOTATION_SUCCESS";
export const SEND_QUOTATION_FAIL = "SEND_QUOTATION_FAIL";
export const SEND_QUOTATION_RESET = "SEND_QUOTATION_RESET";

export const UPDATE_QUOTATION_REQUEST = "UPDATE_QUOTATION_REQUEST";
export const UPDATE_QUOTATION_SUCCESS = "UPDATE_QUOTATION_SUCCESS";
export const UPDATE_QUOTATION_FAIL = "UPDATE_QUOTATION_FAIL";
export const UPDATE_QUOTATION_RESET = "UPDATE_QUOTATION_RESET";

export const UPDATE_SIGNATURE_REQUEST = "UPDATE_SIGNATURE_REQUEST";
export const UPDATE_SIGNATURE_SUCCESS = "UPDATE_SIGNATURE_SUCCESS";
export const UPDATE_SIGNATURE_FAIL = "UPDATE_SIGNATURE_FAIL";
export const UPDATE_SIGNATURE_RESET = "UPDATE_SIGNATURE_RESET";

export const DELETE_QUOTATION_REQUEST = "DELETE_QUOTATION_REQUEST";
export const DELETE_QUOTATION_SUCCESS = "DELETE_QUOTATION_SUCCESS";
export const DELETE_QUOTATION_FAIL = "DELETE_QUOTATION_FAIL";

export const GET_QUOTATION_BY_ID_REQUEST = "GET_QUOTATION_BY_ID_REQUEST";
export const GET_QUOTATION_BY_ID_SUCCESS = "GET_QUOTATION_BY_ID_SUCCESS";
export const GET_QUOTATION_BY_ID_FAIL = "GET_QUOTATION_BY_ID_FAIL";

export const GET_ALL_QUOTATIONS_REQUEST = "GET_ALL_QUOTATIONS_REQUEST";
export const GET_ALL_QUOTATIONS_SUCCESS = "GET_ALL_QUOTATIONS_SUCCESS";
export const GET_ALL_QUOTATIONS_FAIL = "GET_ALL_QUOTATIONS_FAIL";
